### ISSUE TITLE
Create Method for Swear Detection

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/swear-detector#1]
# Motivation
We want to be able to tell if a "swear" is inside a message. We want to implement these in the fastest runtime possible. Ideally in worst case this should only run in ```O(n)```, assuming that all words are unique. Since language is not entirely universal, we'll have to assume that we can only hope that the user will have to go on their own to define what they want to get blocked or not. 

# Task 
- [x] Create a function "parse" a message into a set, delimited by characters. 
- [x] Create a function to test if a message contains a "swear". This takes in a set of messages, and then returns a bool and a set of swears, if any are detected. 
- [x] Import Mocha and chai to demonstrate robust testing, running these scripts in the background to test the absolute strength of these algorithms. 
- [x] Create many tests to empirically demonstrate proper functionality.
