### ISSUE TITLE
Create Method for censoring words

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/swear-detector#3]
# Motivation
We want to be able to censor words, if they choose to only censor words instead of blocking them entirely. 

# Task implementation
- [x] Create a function to take in **a** word and then replace it with a censored phrase if you want. 
- [x] Create a function to collect the delimiters in the order that they were made.
- [x] Generalize the above to be applied to **all** the words in a sentence. 
- [x] Test it out with mocha and chai to confirm its effectiveness and the correctness of the output.
