### ISSUE TITLE
Default Parameterization

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/swear-detector#5]
# Motivation
To make this library easier to use, we want to be able to not have to specify default parameters. Hence, We will adjust all the functions to allow the use of defaulted hard-coded parameters. 

# Task implementation
- [x] Create a file name defaults.js to store default parameters
- [x] Add in as required for index.js
- [x] Go through all the functions and use them as default paramters from defaults.js
- [x] Retest these to make sure that these all pass the tests.
