### ISSUE TITLE
Evasion Checkers

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/swear-detector#6]
# Motivation
We also want to catch people trying to dodger filters. While it is exceedingly a difficult task to block all inappropriate language, over time, with more added default parameterization, we can at least attempt to block out as much as we can, since we'll assume that the edge cases, you will know it when you'll see it. 

# Task implementation
- [x] Create a function to check out if a word is being used to dodge the filter. 
- [x] Create a function to join multiple messages and check if a message is being used to dodge the filter by mapping a message across several messages. 
- [x] Create a function to create new word possibilities by inserting a letter at every character position.
- [x] Create a function to create new word possibilities by deleting a character at every character position.
- [x] Create default parameters to test out these functions
- [x] Go to the tests and then ensure the strength and robustness of the code.
