### ISSUE TITLE
Deploy to NPM.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/swear-detector#7]
# Motivation
Now that all the basic functionality is complete, we want to let other people use this. to this extent, we'll be publishing this repository to NPM where anyone will be able to use this. 

# Task implementation
- [x] Read up on NPM
- [x] Update readme
- [x] Deploy to NPM
- [x] Test out NPM uploading to make sure that the package works in any repo.
