### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/swear-detector#9]
# Motivation
Now that all the basic implementations are done, we want to make this code look nice and readable. We'll modularize this library so that the library can be more easily developed in the future. 

# Task implementation
- [x] Look at other libraries to checkout how they modularize
- [x] Create file structure based on modularity. 
- [ ] Push and Publish.
